### ISSUE TITLE
Schematic issue. GPIO17 not present on ESP8266

### ISSUE THREAD

**Issue by ea3iav** [iodeo/Minitel-ESP32#1]
I see that only ESP32 have GPIO17 pin. I thought the project was about using a cheap and available ESP8266

**Comment by iodeo** [comment]
if i mentioned an esp8266 it was an error .. 
where did you read about esp8266 ?

**Comment by iodeo** [comment]
please note that cheap esp32 module are also available
let us know if you make an equivalent with esp8266 ;)

**Comment by ea3iav** [comment]
Hi there! Now I have that esp32 module. I began using 8266 because there was a project to use zimodem firmware in order to connect to internet. This was my idea, to get the minitel online and connecto to some bbs.

Your implementation is very smart but it is beyond my skills

Thank you

Cesar

Enviado desde mi iPhone

**Comment by iodeo** [comment]
Oh I see !
It is not an issue but a very interesting use case ;)

I don't know this firmware but it should work providing :
1- you define the correct pins for serial comm with minitel
2- you specify the correct serial configuration
3- you put the minitel in the right mode at boot up

1. To identify serial pins you need to check the pinout diagram of your ESP module. 
On my setup, it is connect to GPIO16 (U2_RXD) and GPIO17 (U2_TXD) and that corresponds to UART2 port by default.

2. For serial config, you need to specify:
- the correct uart port number (e.g. UART_NUM_2 for my setup),
- the correct baudrate (e.g 1200 bauds), 
- the  correct mode which is SERIAL_7E1 for minitel (7 data bits + 1 even parity bit + 1 stop bit)

3. On minitel side, you may need to set manually the baud rate (e.g. Fnct+P 2 for 1200 bds) and go in 80 columns ascii mode (Fnct+T A) each time you turn it on.

**Comment by iodeo** [comment]
Hi there,
I was thinking about your usecase ..  wonder if you worked on it last weeks ?

**Comment by ea3iav** [comment]
I have tried but I had no luck at all
I thibk iy would be easier to implement it like on this hayes wifi modem https://github.com/mecparts/RetroWiFiModem

Have a nice day



Enviado desde mi iPhone
