### ISSUE TITLE
SSH client: unable to get past the format SPIFFS prompt

### ISSUE THREAD

**Issue by markostamcar** [iodeo/Minitel-ESP32#2]
Bought your board on Tindie :) The preinstalled Pong example worked fine. Now trying to get the SSH client working but not sure if the enter key is not working (tried Envoi and Ctrl+J) or some other issue.

Bonus question: is there a way to save the baudrate and terminal type setting on the Minitel? :)

![PXL_20211206_080352251](https://user-images.githubusercontent.com/1268630/144809745-6e4382fe-0d5d-457e-abdf-afecbb5c31bb.jpg)
![PXL_20211206_080223557](https://user-images.githubusercontent.com/1268630/144809774-fec12237-7fec-4908-9830-bc5872a03181.jpg)

**Comment by iodeo** [comment]
Thanks for your issue
Actually, it was waiting for an input key from USB port which was confusing.
Please try new version and confirm if it works for you

**Comment by iodeo** [comment]
bonus answer: no setting can be saved on the Minitel but we could make that programmatically with the ESP32.
There are examples on how to do so using Minitel1b library (e.g Minitel1b_Pong). Unfortunately, ssh_client is not straightly compatible with Minitel1b lib cause serial is not handled the "arduino way". It will require a bit of work to make this properly.

**Comment by markostamcar** [comment]
Thank you very much, I'm going to try it straight away! :)

**Comment by markostamcar** [comment]
Yay, it worked, thanks! Ctrl+J works for Enter however the Envoi button just shows "M". (I'll investigate `stty icrnl` to fix this.)
We will be using your dongle for Minitel demonstration at the non-profit Slovenian Computer History Museum ❤️ 
I already have a Node.js CLI application for use with old terminals and it works just fine here on 1st attempt, too :)
More info: https://github.com/markostamcar/muzej.si/blob/master/vt320/README-en.md
Web version: https://zbirka.muzej.si/#english

![PXL_20211206_132230971 PORTRAIT](https://user-images.githubusercontent.com/1268630/144861648-273a59fe-5bc0-493d-913d-793852d6df58.jpg)

**Comment by iodeo** [comment]
So happy to hear this 😃 
"Envoi" will not be straight forward as it is not ascii code
Normally it works with Enter key as well, it corresponds to CR in ascii code
